const STAR_PATH=`M66.9629 0C67.879 0.166652 68.7864 0.351674 69.6846 0.555664L70.0586 0.772461C68.9674 12.7113 65.9785 36.5264 65.9785 36.5264L86.5537 42.1221L87.3721 43.5547L73.4893 48.4336C73.4893 48.4336 88.471 68.4575 96.5049 79.1787C95.9143 79.7262 95.3093 80.2623 94.6895 80.7861L63.0898 57.2207C59.7004 63.8131 46.9882 87.4847 43.667 93.666C42.509 93.4628 41.3648 93.2294 40.2354 92.9668L39.7812 92.5908C41.2618 77.7912 42.674 62.9069 43.501 48.0518C35.4293 45.9499 5.21554 38.569 0 37.2959C0.182283 36.5301 0.385424 35.7704 0.610352 35.0176C14.6821 33.9576 39.8564 31.917 39.8564 31.917L30.9717 15.1201L32.1143 14.4863C38.8474 19.2238 52.083 29.5917 52.1592 29.6514L66.9629 0Z`;
const TEXT_PATH=`M123.26 68.3359V31.8768H109.831V25.6334H144.17V31.8768H130.74V68.3359H123.26ZM161.285 36.7066V43.7746C160.107 43.6568 158.988 43.5979 157.927 43.5979C153.51 43.5979 150.977 45.3649 150.977 51.7261V68.3359H143.968V36.6477H150.859V42.3021C152.568 38.7681 155.63 36.6477 159.459 36.5888C159.989 36.5888 160.755 36.6477 161.285 36.7066ZM165.711 25.6334H172.72V32.7014H165.711V25.6334ZM165.711 36.6477H172.72V68.3359H165.711V36.6477ZM187.323 52.4918C187.323 59.7954 190.916 63.3883 195.51 63.3883C200.222 63.3883 203.52 59.2653 203.52 52.4918C203.52 45.895 200.222 41.6542 195.51 41.6542C190.916 41.6542 187.323 45.1882 187.323 52.4918ZM180.608 25.6334H187.617V40.8885C189.502 37.7668 192.8 35.9409 197.041 35.9409C204.58 35.9409 210.824 42.361 210.824 52.4918C210.824 62.6815 204.58 69.1016 197.041 69.1016C192.8 69.1016 189.502 67.2757 187.617 64.154V68.3359H180.608V25.6334ZM236.113 68.3359V63.9773C234.287 67.2757 231.047 69.1016 226.747 69.1016C219.208 69.1016 216.145 64.154 216.145 56.6148V36.6477H223.155V54.9067C223.155 59.2064 223.744 63.3883 228.986 63.3883C234.228 63.3883 236.113 59.2653 236.113 53.552V36.6477H243.122V68.3359H236.113ZM252.013 36.6477V28.2839H259.022V36.6477H265.384V41.7131H259.022V58.9708C259.022 62.2103 259.788 62.976 262.792 62.976H265.325V68.3359H260.141C253.368 68.3359 252.013 66.51 252.013 60.031V41.7131H247.301V36.6477H252.013ZM299.654 54.4944H276.035C276.506 60.3844 280.629 63.2705 284.635 63.2705C288.345 63.2705 291.173 61.8569 292.409 58.853H299.301C297.887 63.9184 293.057 69.1016 284.929 69.1016C274.739 69.1016 268.908 61.3857 268.908 52.2562C268.908 42.7144 275.446 35.9409 284.458 35.9409C294.176 35.9409 300.302 43.8924 299.654 54.4944ZM284.458 41.4186C281.16 41.4186 276.683 43.4212 276.035 49.3701H292.527C292.351 44.4225 288.581 41.4186 284.458 41.4186Z`;
const STAR_VIEWBOX='0 0 96.5049 93.666';
const OUTER_FX_SCALE=5;
const OUTER_FX_OFFSET=(OUTER_FX_SCALE-1)/2;
const OUTER_SHAPE_RECT=[OUTER_FX_OFFSET/OUTER_FX_SCALE,OUTER_FX_OFFSET/OUTER_FX_SCALE,1/OUTER_FX_SCALE,1/OUTER_FX_SCALE];
const EFFECTS=['strands','galaxy','prismatic','siderays','silk','gradflow'];
const ALL_LAYER_EFFECTS=[...EFFECTS,'vfxshadow'];
const EFFECT_NAMES={strands:'Strands',galaxy:'Galaxy',prismatic:'Prismatic Burst',siderays:'Side Rays',silk:'Silk',gradflow:'GradFlow',vfxshadow:'Chromatic Shadow'};
const GRAD_TYPES=['aurora','mesh','smoke','wave','animated','conic','stripe','silk','linear'];
const PRESETS={
  strands:['#FF4242','#7C3AED','#06B6D4','#EAB308'],
  galaxy:['#FFFFFF','#D4D4D8','#93C5FD','#A78BFA'],
  prismatic:['#FF4242','#7C3AED','#06B6D4','#EAB308'],
  siderays:['#EAB308','#93C5FD','#FFFFFF','#7C3AED'],
  silk:['#8B5CF6','#4F46E5','#22D3EE','#E879F9'],
  gradflow:['#D21570','#8C3FF8','#56FFC3','#0F172A']
};
const defaults={shaderMode:'strands',shaderRole:'fill',gradflowType:'aurora',gradflowNoise:.2,colors:PRESETS.strands.slice(),speed:1,scale:1,intensity:1,opacity:1,overlays:[],autoplayMode:'loop',revealDuration:1,revealDelay:.05,introStartScale:.82,hoverEnabled:true,hoverMode:'follow',hoverPerspective:760,hoverStrength:6,glowEnabled:true,glowAnimated:true,glowColor:'#FFD58A',glowEdgeSensitivity:30,glowRadius:40,glowIntensity:1,glowConeSpread:25,wordmarkAuto:true,wordmarkColor:'#FFFFFF',bgMode:'dark'};
const state=JSON.parse(JSON.stringify(defaults));
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const shapeWrap=$('#shapeWrap'),toastEl=$('#toast'),presetDump=$('#presetDump');
let cleanups=[],renderTimer=0,layerId=1,initialReplayDone=false;

const effectOverflowStyle=document.createElement('style');
effectOverflowStyle.textContent='.outer-fx-layer{left:-200%!important;top:-200%!important;width:500%!important;height:500%!important;overflow:visible!important}.glow-mesh,.glow-light,.border-glow-star{overflow:visible!important}';
document.head.appendChild(effectOverflowStyle);
if(!$('#exportHtmlBtn')){const b=document.createElement('button');b.className='button primary';b.id='exportHtmlBtn';b.type='button';b.textContent='Export HTML';const replay=$('#replayBtn');replay?.parentElement?.insertBefore(b,replay)}

function toast(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),1500)}
function normHex(v){v=(v||'').trim().toUpperCase();if(/^#[0-9A-F]{6}$/.test(v))return v;if(/^#[0-9A-F]{3}$/.test(v))return '#'+v.slice(1).split('').map(c=>c+c).join('');return null}
function starMaskUrl(){const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${STAR_VIEWBOX}"><path d="${STAR_PATH}" fill="white"/></svg>`;return `url("data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}")`}
function wordmarkColor(){return state.wordmarkAuto?(state.bgMode==='light'?'#111113':'#FFFFFF'):state.wordmarkColor}
function exportPreset(){return JSON.parse(JSON.stringify(state))}
function saveFile(name,text,type='text/plain'){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2500)}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Copied')).catch(()=>toast('Copy failed'))}
function shaderRuntimeSource(){return [
  `const VERT300=${JSON.stringify(VERT300)};`,
  `const COMMON=${JSON.stringify(COMMON)};`,
  `const FRAG_STRANDS=${JSON.stringify(FRAG_STRANDS)};`,
  `const FRAG_GALAXY=${JSON.stringify(FRAG_GALAXY)};`,
  `const FRAG_PRISMATIC=${JSON.stringify(FRAG_PRISMATIC)};`,
  `const FRAG_SIDERAYS=${JSON.stringify(FRAG_SIDERAYS)};`,
  `const FRAG_SILK=${JSON.stringify(FRAG_SILK)};`,
  `const FRAG_GRADFLOW=${JSON.stringify(FRAG_GRADFLOW)};`,
  `const FRAG_SHADOW=${JSON.stringify(FRAG_SHADOW)};`,
  `const GRAD_TYPE_IDS=${JSON.stringify(GRAD_TYPE_IDS)};`,
  hexRgb.toString(),compileGL.toString(),makeProgram.toString(),bindQuad.toString(),paletteUniform.toString(),runShaderCanvas.toString(),makeShapeTexture.toString(),runVfxShadowCanvas.toString()
].join('\n')}
function buildStandaloneHtml(){
  const p=exportPreset(),runtime=shaderRuntimeSource(),presetJson=JSON.stringify(p).replace(/</g,'\\u003c');
  const bg=p.bgMode==='light'?'#f4f4f5':p.bgMode==='transparent'?'transparent':'#0f0f12';
  const starJson=JSON.stringify(STAR_PATH),textJson=JSON.stringify(TEXT_PATH),viewJson=JSON.stringify(STAR_VIEWBOX);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tribute animated mark</title>
<style>
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;background:${bg}}body{overflow:hidden}
.animation-root{position:fixed;inset:0;display:grid;place-items:center;background:${bg};overflow:hidden}
.logo{position:relative;width:min(78vw,940px);aspect-ratio:302/94;overflow:visible;filter:drop-shadow(0 18px 68px rgba(0,0,0,.28))}
.logo-composition,.wordmark-svg{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.wordmark-svg{z-index:8;pointer-events:none}
.star-scene{position:absolute;left:0;top:0;width:31.955%;height:100%;z-index:10;transform-origin:50% 50%;transform-style:preserve-3d;will-change:transform;overflow:visible}
.star-intro{position:absolute;inset:0;transform-origin:center;will-change:transform,opacity;z-index:2;overflow:visible}
.star-svg,.shader-stack,.shader-layer,.border-glow-star,.glow-mesh,.glow-light{position:absolute;inset:0;width:100%;height:100%}.star-svg,.glow-mesh,.glow-light{overflow:visible}
.shader-stack{z-index:2}.shader-layer{pointer-events:none}.outer-fx-layer{position:absolute;left:-200%;top:-200%;width:500%;height:500%;z-index:1;pointer-events:none;overflow:visible}.outer-fx-canvas{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}
.border-glow-star{z-index:4;pointer-events:none;--cursor-angle:45deg;--edge-proximity:0;--edge-sensitivity:30;--cone-spread:25;overflow:visible}.glow-mesh,.glow-light{transition:opacity .25s ease-out}.border-glow-star.glow-disabled{display:none}
.glow-mesh{opacity:calc(max(0,(var(--edge-proximity) - (var(--edge-sensitivity) + 18)) / max(1,(82 - var(--edge-sensitivity)))));mask-image:conic-gradient(from var(--cursor-angle) at center,#000 calc(var(--cone-spread)*1%),transparent calc((var(--cone-spread) + 15)*1%),transparent calc((100 - var(--cone-spread) - 15)*1%),#000 calc((100 - var(--cone-spread))*1%));-webkit-mask-image:conic-gradient(from var(--cursor-angle) at center,#000 calc(var(--cone-spread)*1%),transparent calc((var(--cone-spread) + 15)*1%),transparent calc((100 - var(--cone-spread) - 15)*1%),#000 calc((100 - var(--cone-spread))*1%));mix-blend-mode:screen}
.glow-light{opacity:calc(max(0,(var(--edge-proximity) - var(--edge-sensitivity)) / max(1,(100 - var(--edge-sensitivity)))));mask-image:conic-gradient(from var(--cursor-angle) at center,#000 2.5%,transparent 11%,transparent 89%,#000 97.5%);-webkit-mask-image:conic-gradient(from var(--cursor-angle) at center,#000 2.5%,transparent 11%,transparent 89%,#000 97.5%);mix-blend-mode:plus-lighter}
</style>
</head>
<body><div class="animation-root" id="animationRoot"><div class="logo" id="logo"></div></div>
<script>window.SMS_V2_PRESET=${presetJson};</script>
<script>${runtime}</script>
<script>
const PRESET=window.SMS_V2_PRESET;
const STAR_PATH=${starJson},TEXT_PATH=${textJson},STAR_VIEWBOX=${viewJson};
const OUTER_SHAPE_RECT=[.4,.4,.2,.2];
const root=document.getElementById('animationRoot'),logo=document.getElementById('logo');
const wordColor=()=>PRESET.wordmarkAuto?(PRESET.bgMode==='light'?'#111113':'#FFFFFF'):PRESET.wordmarkColor;
const starMask=()=>{const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+STAR_VIEWBOX+'"><path d="'+STAR_PATH+'" fill="white"/></svg>';return 'url("data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)+'")'};
function glowMarkup(){const r=PRESET.glowRadius/40,intensity=PRESET.glowIntensity,c=PRESET.glowColor,mesh=PRESET.colors.slice(0,3);return '<div class="border-glow-star '+(PRESET.glowEnabled?'':'glow-disabled')+'" id="borderGlowStar" style="--edge-sensitivity:'+PRESET.glowEdgeSensitivity+';--cone-spread:'+PRESET.glowConeSpread+'"><svg class="glow-mesh" viewBox="'+STAR_VIEWBOX+'" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="meshGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="'+mesh[0]+'"/><stop offset=".52" stop-color="'+mesh[1]+'"/><stop offset="1" stop-color="'+mesh[2]+'"/></linearGradient></defs><path d="'+STAR_PATH+'" fill="none" stroke="url(#meshGradient)" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" opacity="'+Math.min(1,.9*intensity)+'"/><path d="'+STAR_PATH+'" fill="none" stroke="url(#meshGradient)" stroke-width="'+(4*r)+'" stroke-linecap="round" stroke-linejoin="round" opacity="'+Math.min(1,.26*intensity)+'" style="filter:blur('+(2.4*r)+'px)"/></svg><svg class="glow-light" viewBox="'+STAR_VIEWBOX+'" xmlns="http://www.w3.org/2000/svg"><path d="'+STAR_PATH+'" fill="none" stroke="'+c+'" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" opacity="'+Math.min(1,intensity)+'"/><path d="'+STAR_PATH+'" fill="none" stroke="'+c+'" stroke-width="'+(2.3*r)+'" stroke-linecap="round" stroke-linejoin="round" opacity="'+Math.min(1,.58*intensity)+'" style="filter:blur('+(.8*r)+'px)"/><path d="'+STAR_PATH+'" fill="none" stroke="'+c+'" stroke-width="'+(4.8*r)+'" stroke-linecap="round" stroke-linejoin="round" opacity="'+Math.min(1,.34*intensity)+'" style="filter:blur('+(2.2*r)+'px)"/><path d="'+STAR_PATH+'" fill="none" stroke="'+c+'" stroke-width="'+(8.5*r)+'" stroke-linecap="round" stroke-linejoin="round" opacity="'+Math.min(1,.18*intensity)+'" style="filter:blur('+(5*r)+'px)"/></svg></div>'}
function markup(){return '<div class="logo-composition"><svg class="wordmark-svg" viewBox="0 0 302 94" xmlns="http://www.w3.org/2000/svg"><path d="'+TEXT_PATH+'" fill="'+wordColor()+'"/></svg><div class="star-scene" id="starScene"><div class="star-intro" id="starIntro"><div class="outer-fx-layer" id="outerFxLayer"></div><svg class="star-svg" viewBox="'+STAR_VIEWBOX+'" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="fallbackGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="'+PRESET.colors[0]+'"/><stop offset=".5" stop-color="'+PRESET.colors[1]+'"/><stop offset="1" stop-color="'+PRESET.colors[2]+'"/></linearGradient></defs><path id="baseFallbackPath" d="'+STAR_PATH+'" fill="'+(PRESET.shaderRole==='reveal'?PRESET.colors[0]:'transparent')+'"/></svg><div class="shader-stack" id="shaderStack"></div>'+glowMarkup()+'</div></div></div>'}
function mask(c){const m=starMask();c.style.webkitMaskImage=m;c.style.maskImage=m;c.style.webkitMaskRepeat=c.style.maskRepeat='no-repeat';c.style.webkitMaskPosition=c.style.maskPosition='center';c.style.webkitMaskSize=c.style.maskSize='100% 100%'}
function fill(container,o,base=false){const c=document.createElement('canvas');c.className='shader-layer';c.style.zIndex=String(o.z||2);c.style.opacity=String(o.opacity??1);c.style.mixBlendMode=o.blend||'normal';if(base)c.dataset.base='1';mask(c);container.appendChild(c);return runShaderCanvas(c,{mode:o.mode,colors:PRESET.colors,speed:PRESET.speed,scale:PRESET.scale,intensity:PRESET.intensity,target:root,gradType:o.gradType||PRESET.gradflowType,noise:o.noise??PRESET.gradflowNoise})}
function shadow(container,o,z){const c=document.createElement('canvas');c.className='outer-fx-canvas';c.style.zIndex=String(z);c.style.opacity=String(o.opacity);c.style.mixBlendMode=o.blend||'screen';container.appendChild(c);return runVfxShadowCanvas(c,{path:STAR_PATH,viewW:96.5049,viewH:93.666,colors:PRESET.colors,intensity:PRESET.intensity,reach:o.reach??1,jitter:o.jitter??.55,lightMode:o.lightMode||'pointer',target:root,shapeRect:OUTER_SHAPE_RECT})}
function perspective(){const scene=document.getElementById('starScene');if(!scene)return;scene.addEventListener('pointermove',e=>{if(!PRESET.hoverEnabled)return;const r=scene.getBoundingClientRect(),nx=((e.clientX-r.left)/r.width-.5)*2,ny=((e.clientY-r.top)/r.height-.5)*2,s=PRESET.hoverStrength;let rx=-ny*s,ry=nx*s;if(PRESET.hoverMode==='inverse'){rx*=-1;ry*=-1}else if(PRESET.hoverMode==='diagonal'){rx=-(nx+ny)*s*.55;ry=(nx-ny)*s*.55}scene.style.transition='transform 70ms linear';scene.style.transform='perspective('+PRESET.hoverPerspective+'px) rotateX('+rx+'deg) rotateY('+ry+'deg) scale(1.018)'});scene.addEventListener('pointerleave',()=>{scene.style.transition='transform 420ms cubic-bezier(.2,.8,.2,1)';scene.style.transform='perspective('+PRESET.hoverPerspective+'px) rotateX(0deg) rotateY(0deg) scale(1)'})}
function glow(){const scene=document.getElementById('starScene'),g=document.getElementById('borderGlowStar');if(!scene||!g)return;let hovered=false,t0=performance.now();const update=(x,y)=>{const r=scene.getBoundingClientRect(),cx=r.width/2,cy=r.height/2,dx=x-cx,dy=y-cy,kx=dx===0?Infinity:cx/Math.abs(dx),ky=dy===0?Infinity:cy/Math.abs(dy),edge=Math.min(Math.max(1/Math.min(kx,ky),0),1),angle=((Math.atan2(dy,dx)*180/Math.PI)+90+360)%360;g.style.setProperty('--edge-proximity',(edge*100).toFixed(2));g.style.setProperty('--cursor-angle',angle.toFixed(2)+'deg')};scene.addEventListener('pointerenter',e=>{hovered=true;const r=scene.getBoundingClientRect();update(e.clientX-r.left,e.clientY-r.top)});scene.addEventListener('pointermove',e=>{hovered=true;const r=scene.getBoundingClientRect();update(e.clientX-r.left,e.clientY-r.top)});scene.addEventListener('pointerleave',()=>{hovered=false;if(!PRESET.glowAnimated)g.style.setProperty('--edge-proximity','0')});const loop=now=>{if(!hovered&&PRESET.glowEnabled&&PRESET.glowAnimated){const t=(now-t0)/1000,angle=110+(t*70)%355,proximity=72+28*(.5+.5*Math.sin(t*1.15));g.style.setProperty('--cursor-angle',angle+'deg');g.style.setProperty('--edge-proximity',String(proximity))}requestAnimationFrame(loop)};requestAnimationFrame(loop)}
function replayAnimation(){const intro=document.getElementById('starIntro');if(!intro)return;const duration=PRESET.revealDuration*1000,delay=PRESET.revealDelay*1000;intro.getAnimations().forEach(a=>a.cancel());intro.animate([{transform:'scale('+PRESET.introStartScale+') translateZ(0)',opacity:0,filter:'blur(5px)'},{transform:'scale(1.025) translateZ(0)',opacity:1,filter:'blur(0px)',offset:.72},{transform:'scale(1) translateZ(0)',opacity:1,filter:'blur(0px)'}],{duration,delay,easing:'cubic-bezier(.16,.84,.18,1)',fill:'both'});if(PRESET.shaderRole==='reveal'){const base=intro.querySelector('[data-base="1"]');base?.animate([{opacity:0},{opacity:PRESET.opacity,offset:.58},{opacity:0}],{duration,delay,easing:'ease-in-out',fill:'both'})}}
logo.innerHTML=markup();const stack=document.getElementById('shaderStack'),outer=document.getElementById('outerFxLayer');try{fill(stack,{mode:PRESET.shaderMode,opacity:PRESET.opacity,blend:'normal',z:2,gradType:PRESET.gradflowType,noise:PRESET.gradflowNoise},true)}catch(e){const fb=document.getElementById('baseFallbackPath');if(fb){fb.setAttribute('fill','url(#fallbackGradient)');fb.setAttribute('opacity','1')}}let z=3,oz=1;for(const l of PRESET.overlays||[]){try{if(l.mode==='vfxshadow')shadow(outer,l,oz++);else fill(stack,{mode:l.mode,opacity:l.opacity,blend:l.blend,z:z++,gradType:l.gradType,noise:l.noise})}catch(e){console.error(e)}}perspective();glow();requestAnimationFrame(replayAnimation);window.replayAnimation=replayAnimation;
</script></body></html>`
}
function fmt(v,d=2){return Number(v).toFixed(d).replace(/\.00$/,'').replace(/(\.\d)0$/,'$1')}
function updateOutput(id,value,unit=''){const out=$('#'+id+'Val');if(out)out.textContent=`${fmt(value)}${unit}`}
function syncBackground(){const card=$('#stageCard'),checker=$('#checker');if(state.bgMode==='light'){card.style.background='radial-gradient(circle at 50% 38%,rgba(0,0,0,.035),transparent 35%),#f4f4f5';checker.style.opacity='.08'}else if(state.bgMode==='transparent'){card.style.background='transparent';checker.style.opacity='.2'}else{card.style.background='radial-gradient(circle at 50% 38%,rgba(255,255,255,.05),transparent 35%),#0f0f12';checker.style.opacity='.18'}}
function updateStatus(){const shadowCount=state.overlays.filter(x=>x.mode==='vfxshadow').length,fillCount=state.overlays.length-shadowCount;$('#activeEffectLabel').textContent=`${EFFECT_NAMES[state.shaderMode]} · ${fillCount} fill overlay${fillCount===1?'':'s'}${shadowCount?` · ${shadowCount} shadow`:''}`;$('#motionSummary').textContent=`${fmt(state.revealDuration)}s · clean`;$('#layerCount').textContent=`${state.overlays.length} overlay${state.overlays.length===1?'':'s'}`;presetDump.value=JSON.stringify(exportPreset(),null,2)}
function syncUi(){
  ['speed','scale','intensity','opacity','gradflowNoise','revealDuration','revealDelay','introStartScale','hoverStrength','glowEdgeSensitivity','glowRadius','glowIntensity','glowConeSpread'].forEach(k=>{const el=$('#'+k);if(el)el.value=state[k];updateOutput(k,state[k],k==='glowRadius'?'px':'')});
  ['shaderMode','shaderRole','autoplayMode','hoverMode','hoverPerspective','bgMode'].forEach(k=>{const el=$('#'+k);if(el)el.value=String(state[k])});
  state.colors.forEach((v,i)=>{const n=i+1;$('#c'+n).value=v;$('#c'+n+'Text').value=v});
  $('#glowColor').value=state.glowColor;$('#glowColorText').value=state.glowColor;$('#wordmarkColor').value=state.wordmarkColor;$('#wordmarkColorText').value=state.wordmarkColor;
  [['glowEnabled',state.glowEnabled],['glowAnimated',state.glowAnimated],['hoverEnabled',state.hoverEnabled],['wordmarkAuto',state.wordmarkAuto]].forEach(([id,on])=>$('#'+id)?.classList.toggle('on',!!on));
  $$('.effect-card').forEach(c=>c.classList.toggle('is-active',c.dataset.effect===state.shaderMode));
  $$('#shaderRoleSegmented .segment').forEach(b=>b.classList.toggle('is-active',b.dataset.role===state.shaderRole));
  $$('#autoplaySegmented .segment').forEach(b=>b.classList.toggle('is-active',b.dataset.autoplay===state.autoplayMode));
  $$('#gradflowTypeGrid .grad-type').forEach(b=>b.classList.toggle('is-active',b.dataset.gradType===state.gradflowType));
  $('#baseGradflowSettings').hidden=state.shaderMode!=='gradflow';syncBackground();renderLayerList();updateStatus();
}
function bindHex(colorId,textId,onChange){const c=$('#'+colorId),t=$('#'+textId);c.addEventListener('input',()=>{const v=c.value.toUpperCase();t.value=v;onChange(v)});t.addEventListener('change',()=>{const v=normHex(t.value);if(!v){t.value=c.value.toUpperCase();return}c.value=v;t.value=v;onChange(v)})}
function effectOptions(selected){return ALL_LAYER_EFFECTS.map(m=>`<option value="${m}" ${m===selected?'selected':''}>${EFFECT_NAMES[m]}</option>`).join('')}
function gradTypeOptions(selected){return GRAD_TYPES.map(t=>`<option value="${t}" ${t===selected?'selected':''}>${t[0].toUpperCase()+t.slice(1)}</option>`).join('')}
function renderLayerList(){
  const root=$('#layerList');if(!root)return;
  if(!state.overlays.length){root.innerHTML='<div class="layer-empty">Нет дополнительных слоёв. Добавь GradFlow/другой fill или внешний Chromatic Shadow.</div>';return}
  root.innerHTML=state.overlays.map(layer=>{
    const extra=layer.mode==='gradflow'?`<div class="layer-extra"><label>Gradient type<select class="layer-grad-type">${gradTypeOptions(layer.gradType||'aurora')}</select></label><label>Noise <span class="inline-value">${fmt(layer.noise??.2)}</span><input class="layer-noise" type="range" min="0" max="0.5" step="0.01" value="${layer.noise??.2}"></label></div>`:layer.mode==='vfxshadow'?`<div class="layer-extra"><label>Light<select class="layer-light"><option value="pointer" ${layer.lightMode!=='orbit'?'selected':''}>Pointer</option><option value="orbit" ${layer.lightMode==='orbit'?'selected':''}>Auto orbit</option></select></label><label>Reach <span class="inline-value">${fmt(layer.reach??1)}</span><input class="layer-reach" type="range" min="0.45" max="1.8" step="0.05" value="${layer.reach??1}"></label><label>Jitter <span class="inline-value">${fmt(layer.jitter??.55)}</span><input class="layer-jitter" type="range" min="0" max="1.5" step="0.05" value="${layer.jitter??.55}"></label><div class="layer-kind">outside silhouette effect</div></div>`:'';
    return `<div class="layer-row" data-layer-id="${layer.id}"><div class="layer-kind">${layer.mode==='vfxshadow'?'Outer WebGL':'Inside star'}</div><div class="layer-main"><select class="layer-effect">${effectOptions(layer.mode)}</select><select class="layer-blend"><option value="screen" ${layer.blend==='screen'?'selected':''}>Screen</option><option value="plus-lighter" ${layer.blend==='plus-lighter'?'selected':''}>Plus lighter</option><option value="lighten" ${layer.blend==='lighten'?'selected':''}>Lighten</option><option value="overlay" ${layer.blend==='overlay'?'selected':''}>Overlay</option><option value="normal" ${layer.blend==='normal'?'selected':''}>Normal</option></select><button class="layer-remove" type="button" title="Remove">×</button></div><label class="layer-opacity"><span><b>Opacity</b><em>${Math.round(layer.opacity*100)}%</em></span><input class="layer-opacity-input" type="range" min="0.05" max="1" step="0.05" value="${layer.opacity}"></label>${extra}</div>`
  }).join('');
  $$('.layer-row',root).forEach(row=>{
    const id=Number(row.dataset.layerId),get=()=>state.overlays.find(x=>x.id===id);
    $('.layer-effect',row).addEventListener('change',e=>{const l=get();l.mode=e.target.value;if(l.mode==='gradflow'){l.gradType=l.gradType||'aurora';l.noise=l.noise??.2}else if(l.mode==='vfxshadow'){l.reach=l.reach??1;l.jitter=l.jitter??.55;l.lightMode=l.lightMode||'pointer';l.blend=l.blend==='normal'?'screen':l.blend}syncUi();scheduleRender()});
    $('.layer-blend',row).addEventListener('change',e=>{get().blend=e.target.value;scheduleRender()});
    $('.layer-opacity-input',row).addEventListener('input',e=>{get().opacity=parseFloat(e.target.value);$('em',row).textContent=Math.round(get().opacity*100)+'%';updateStatus();scheduleRender()});
    $('.layer-remove',row).addEventListener('click',()=>{state.overlays=state.overlays.filter(x=>x.id!==id);syncUi();scheduleRender()});
    $('.layer-grad-type',row)?.addEventListener('change',e=>{get().gradType=e.target.value;scheduleRender()});
    $('.layer-noise',row)?.addEventListener('input',e=>{get().noise=parseFloat(e.target.value);$('.inline-value',e.target.closest('label')).textContent=fmt(get().noise);scheduleRender()});
    $('.layer-light',row)?.addEventListener('change',e=>{get().lightMode=e.target.value;scheduleRender()});
    $('.layer-reach',row)?.addEventListener('input',e=>{get().reach=parseFloat(e.target.value);$('.inline-value',e.target.closest('label')).textContent=fmt(get().reach);scheduleRender()});
    $('.layer-jitter',row)?.addEventListener('input',e=>{get().jitter=parseFloat(e.target.value);$('.inline-value',e.target.closest('label')).textContent=fmt(get().jitter);scheduleRender()});
  })
}
function buildGlowMarkup(){const r=state.glowRadius/40,intensity=state.glowIntensity,c=state.glowColor,mesh=state.colors.slice(0,3);return `<div class="border-glow-star ${state.glowEnabled?'':'glow-disabled'}" id="borderGlowStar" style="--edge-sensitivity:${state.glowEdgeSensitivity};--cone-spread:${state.glowConeSpread}"><svg class="glow-mesh" viewBox="${STAR_VIEWBOX}" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="meshGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${mesh[0]}"/><stop offset=".52" stop-color="${mesh[1]}"/><stop offset="1" stop-color="${mesh[2]}"/></linearGradient></defs><path d="${STAR_PATH}" fill="none" stroke="url(#meshGradient)" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" opacity="${Math.min(1,.9*intensity)}"/><path d="${STAR_PATH}" fill="none" stroke="url(#meshGradient)" stroke-width="${4*r}" stroke-linecap="round" stroke-linejoin="round" opacity="${Math.min(1,.26*intensity)}" style="filter:blur(${2.4*r}px)"/></svg><svg class="glow-light" viewBox="${STAR_VIEWBOX}" xmlns="http://www.w3.org/2000/svg"><path d="${STAR_PATH}" fill="none" stroke="${c}" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" opacity="${Math.min(1,intensity)}"/><path d="${STAR_PATH}" fill="none" stroke="${c}" stroke-width="${2.3*r}" stroke-linecap="round" stroke-linejoin="round" opacity="${Math.min(1,.58*intensity)}" style="filter:blur(${.8*r}px)"/><path d="${STAR_PATH}" fill="none" stroke="${c}" stroke-width="${4.8*r}" stroke-linecap="round" stroke-linejoin="round" opacity="${Math.min(1,.34*intensity)}" style="filter:blur(${2.2*r}px)"/><path d="${STAR_PATH}" fill="none" stroke="${c}" stroke-width="${8.5*r}" stroke-linecap="round" stroke-linejoin="round" opacity="${Math.min(1,.18*intensity)}" style="filter:blur(${5*r}px)"/></svg></div>`}
function buildMarkup(){return `<div class="logo-composition"><svg class="wordmark-svg" viewBox="0 0 302 94" xmlns="http://www.w3.org/2000/svg"><path d="${TEXT_PATH}" fill="${wordmarkColor()}"/></svg><div class="star-scene" id="starScene"><div class="star-intro" id="starIntro"><div class="outer-fx-layer" id="outerFxLayer"></div><svg class="star-svg" viewBox="${STAR_VIEWBOX}" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="fallbackGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${state.colors[0]}"/><stop offset=".5" stop-color="${state.colors[1]}"/><stop offset="1" stop-color="${state.colors[2]}"/></linearGradient></defs><path id="baseFallbackPath" d="${STAR_PATH}" fill="${state.shaderRole==='reveal'?state.colors[0]:'transparent'}"/></svg><div class="shader-stack" id="shaderStack"></div>${buildGlowMarkup()}</div></div></div>`}
function applyMask(canvas){const mask=starMaskUrl();canvas.style.webkitMaskImage=mask;canvas.style.maskImage=mask;canvas.style.webkitMaskRepeat=canvas.style.maskRepeat='no-repeat';canvas.style.webkitMaskPosition=canvas.style.maskPosition='center';canvas.style.webkitMaskSize=canvas.style.maskSize='100% 100%'}
function createFillLayer(container,opts,isBase=false){const c=document.createElement('canvas');c.className='shader-layer';c.style.zIndex=String(opts.z||2);c.style.opacity=String(opts.opacity??1);c.style.mixBlendMode=opts.blend||'normal';if(isBase)c.dataset.base='1';applyMask(c);container.appendChild(c);const cleanup=runShaderCanvas(c,{mode:opts.mode,colors:state.colors,speed:state.speed*(opts.speedMul||1),scale:state.scale*(opts.scaleMul||1),intensity:state.intensity,target:$('#stageCard'),gradType:opts.gradType||state.gradflowType,noise:opts.noise??state.gradflowNoise});cleanups.push(cleanup);return c}
function createShadowLayer(container,layer,z){const c=document.createElement('canvas');c.className='outer-fx-canvas';c.style.zIndex=String(z);c.style.opacity=String(layer.opacity);c.style.mixBlendMode=layer.blend||'screen';container.appendChild(c);const cleanup=runVfxShadowCanvas(c,{path:STAR_PATH,viewW:96.5049,viewH:93.666,colors:state.colors,intensity:state.intensity,reach:layer.reach??1,jitter:layer.jitter??.55,lightMode:layer.lightMode||'pointer',target:$('#stageCard'),shapeRect:OUTER_SHAPE_RECT});cleanups.push(cleanup)}
function bindPerspective(){const scene=$('#starScene');if(!scene)return()=>{};const move=e=>{if(!state.hoverEnabled)return;const r=scene.getBoundingClientRect(),nx=((e.clientX-r.left)/r.width-.5)*2,ny=((e.clientY-r.top)/r.height-.5)*2,s=state.hoverStrength;let rx=-ny*s,ry=nx*s;if(state.hoverMode==='inverse'){rx*=-1;ry*=-1}else if(state.hoverMode==='diagonal'){rx=-(nx+ny)*s*.55;ry=(nx-ny)*s*.55}scene.style.transition='transform 70ms linear';scene.style.transform=`perspective(${state.hoverPerspective}px) rotateX(${rx}deg) rotateY(${ry}deg) scale(1.018)`};const leave=()=>{scene.style.transition='transform 420ms cubic-bezier(.2,.8,.2,1)';scene.style.transform=`perspective(${state.hoverPerspective}px) rotateX(0deg) rotateY(0deg) scale(1)`};scene.addEventListener('pointermove',move);scene.addEventListener('pointerleave',leave);return()=>{scene.removeEventListener('pointermove',move);scene.removeEventListener('pointerleave',leave)}}
function bindGlow(){const scene=$('#starScene'),glow=$('#borderGlowStar');if(!scene||!glow)return()=>{};let hovered=false,raf=0,t0=performance.now();const update=(x,y)=>{const r=scene.getBoundingClientRect(),cx=r.width/2,cy=r.height/2,dx=x-cx,dy=y-cy,kx=dx===0?Infinity:cx/Math.abs(dx),ky=dy===0?Infinity:cy/Math.abs(dy),edge=Math.min(Math.max(1/Math.min(kx,ky),0),1),angle=((Math.atan2(dy,dx)*180/Math.PI)+90+360)%360;glow.style.setProperty('--edge-proximity',(edge*100).toFixed(2));glow.style.setProperty('--cursor-angle',`${angle.toFixed(2)}deg`)};const move=e=>{hovered=true;const r=scene.getBoundingClientRect();update(e.clientX-r.left,e.clientY-r.top)};const enter=e=>{hovered=true;move(e)};const leave=()=>{hovered=false;if(!state.glowAnimated)glow.style.setProperty('--edge-proximity','0')};scene.addEventListener('pointerenter',enter);scene.addEventListener('pointermove',move);scene.addEventListener('pointerleave',leave);const loop=now=>{if(!hovered&&state.glowEnabled&&state.glowAnimated){const t=(now-t0)/1000,angle=110+(t*70)%355,proximity=72+28*(.5+.5*Math.sin(t*1.15));glow.style.setProperty('--cursor-angle',`${angle}deg`);glow.style.setProperty('--edge-proximity',String(proximity))}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);scene.removeEventListener('pointerenter',enter);scene.removeEventListener('pointermove',move);scene.removeEventListener('pointerleave',leave)}}
function renderPreview(){
  cleanups.forEach(fn=>{try{fn()}catch{}});cleanups=[];shapeWrap.innerHTML=buildMarkup();
  const stack=$('#shaderStack'),outer=$('#outerFxLayer');
  try{createFillLayer(stack,{mode:state.shaderMode,opacity:state.opacity,blend:'normal',z:2,gradType:state.gradflowType,noise:state.gradflowNoise},true)}catch(e){console.error(e);const fb=$('#baseFallbackPath');if(fb){fb.setAttribute('fill','url(#fallbackGradient)');fb.setAttribute('opacity','1')}toast('WebGL unavailable · fallback shown')}
  let z=3,oz=1;for(const layer of state.overlays){try{if(layer.mode==='vfxshadow')createShadowLayer(outer,layer,oz++);else createFillLayer(stack,{mode:layer.mode,opacity:layer.opacity,blend:layer.blend,z:z++,gradType:layer.gradType,noise:layer.noise})}catch(e){console.error(e)}}
  cleanups.push(bindPerspective());cleanups.push(bindGlow());syncBackground();updateStatus();
  if(state.autoplayMode==='auto')requestAnimationFrame(replayIntro);else if(!initialReplayDone){initialReplayDone=true;requestAnimationFrame(replayIntro)}
}
function replayIntro(){const intro=$('#starIntro');if(!intro)return;const duration=state.revealDuration*1000,delay=state.revealDelay*1000;intro.getAnimations().forEach(a=>a.cancel());intro.animate([{transform:`scale(${state.introStartScale}) translateZ(0)`,opacity:0,filter:'blur(5px)'},{transform:'scale(1.025) translateZ(0)',opacity:1,filter:'blur(0px)',offset:.72},{transform:'scale(1) translateZ(0)',opacity:1,filter:'blur(0px)'}],{duration,delay,easing:'cubic-bezier(.16,.84,.18,1)',fill:'both'});if(state.shaderRole==='reveal'){const base=$('[data-base="1"]',intro);base?.getAnimations().forEach(a=>a.cancel());base?.animate([{opacity:0},{opacity:state.opacity,offset:.58},{opacity:0}],{duration,delay,easing:'ease-in-out',fill:'both'})}}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(renderPreview,55)}
function addLayer(mode='gradflow'){state.overlays.push({id:layerId++,mode,blend:mode==='vfxshadow'?'screen':'screen',opacity:mode==='vfxshadow'?.72:.55,gradType:'aurora',noise:.18,reach:1,jitter:.55,lightMode:'pointer'});syncUi();scheduleRender()}
function normalizePreset(p){const next={...defaults,...p};next.colors=(Array.isArray(p.colors)?p.colors:defaults.colors).slice(0,4).map(x=>normHex(x)||'#FFFFFF');while(next.colors.length<4)next.colors.push(next.colors[next.colors.length-1]||'#FFFFFF');next.shaderMode=EFFECTS.includes(next.shaderMode)?next.shaderMode:'strands';next.gradflowType=GRAD_TYPES.includes(next.gradflowType)?next.gradflowType:'aurora';next.overlays=(Array.isArray(p.overlays)?p.overlays:[]).map(x=>({id:x.id||layerId++,mode:ALL_LAYER_EFFECTS.includes(x.mode)?x.mode:'gradflow',blend:x.blend||'screen',opacity:Number.isFinite(+x.opacity)?+x.opacity:.55,gradType:GRAD_TYPES.includes(x.gradType)?x.gradType:'aurora',noise:Number.isFinite(+x.noise)?+x.noise:.2,reach:Number.isFinite(+x.reach)?+x.reach:1,jitter:Number.isFinite(+x.jitter)?+x.jitter:.55,lightMode:x.lightMode==='orbit'?'orbit':'pointer'}));return next}
function applyPreset(p){Object.assign(state,normalizePreset(p));layerId=Math.max(1,...state.overlays.map(x=>x.id+1));syncUi();renderPreview();replayIntro()}
function extractLegacy(html){const out=exportPreset();const m=html.match(/runShaderCanvas\(shaderCanvas,\s*(\{[\s\S]*?\})\s*\)/);if(m){try{const obj=(new Function(`return (${m[1]})`))();if(EFFECTS.includes(obj.mode))out.shaderMode=obj.mode;if(obj.speed!=null)out.speed=obj.speed;if(obj.scale!=null)out.scale=obj.scale;if(obj.intensity!=null)out.intensity=obj.intensity;if(Array.isArray(obj.colors))out.colors=obj.colors.slice(0,4).map(v=>normHex(v)||'#FFFFFF')}catch{}}return out}
function handleImport(file){const r=new FileReader();r.onload=()=>{const text=String(r.result||'');try{if(file.name.match(/\.json$/i)){applyPreset(JSON.parse(text));toast('Preset loaded');return}const m=text.match(/window\.SMS_V2_PRESET\s*=\s*(\{[\s\S]*?\});/);applyPreset(m?JSON.parse(m[1]):extractLegacy(text));toast('Settings imported')}catch(e){console.error(e);toast('Import failed')}};r.readAsText(file)}

// Base effect selection
$$('.effect-card').forEach(btn=>btn.addEventListener('click',()=>{state.shaderMode=btn.dataset.effect;state.colors=PRESETS[state.shaderMode].slice();syncUi();scheduleRender()}));
$$('#gradflowTypeGrid .grad-type').forEach(btn=>btn.addEventListener('click',()=>{state.gradflowType=btn.dataset.gradType;syncUi();scheduleRender()}));
$('#shaderRoleSegmented').addEventListener('click',e=>{const b=e.target.closest('[data-role]');if(!b)return;state.shaderRole=b.dataset.role;syncUi();scheduleRender()});
$('#autoplaySegmented').addEventListener('click',e=>{const b=e.target.closest('[data-autoplay]');if(!b)return;state.autoplayMode=b.dataset.autoplay;syncUi()});

// Base sliders / selects
[['speed','speed'],['scale','scale'],['intensity','intensity'],['opacity','opacity'],['gradflowNoise','gradflowNoise'],['revealDuration','revealDuration'],['revealDelay','revealDelay'],['introStartScale','introStartScale'],['hoverStrength','hoverStrength'],['glowEdgeSensitivity','glowEdgeSensitivity'],['glowRadius','glowRadius'],['glowIntensity','glowIntensity'],['glowConeSpread','glowConeSpread']].forEach(([id,key])=>$('#'+id).addEventListener('input',e=>{state[key]=parseFloat(e.target.value);updateOutput(id,state[key],id==='glowRadius'?'px':'');updateStatus();scheduleRender()}));
[['hoverMode','hoverMode'],['hoverPerspective','hoverPerspective'],['bgMode','bgMode']].forEach(([id,key])=>$('#'+id).addEventListener('change',e=>{state[key]=id==='hoverPerspective'?parseFloat(e.target.value):e.target.value;syncBackground();scheduleRender()}));

bindHex('c1','c1Text',v=>{state.colors[0]=v;scheduleRender()});bindHex('c2','c2Text',v=>{state.colors[1]=v;scheduleRender()});bindHex('c3','c3Text',v=>{state.colors[2]=v;scheduleRender()});bindHex('c4','c4Text',v=>{state.colors[3]=v;scheduleRender()});
bindHex('glowColor','glowColorText',v=>{state.glowColor=v;scheduleRender()});bindHex('wordmarkColor','wordmarkColorText',v=>{state.wordmarkColor=v;scheduleRender()});
[['glowEnabled','glowEnabled'],['glowAnimated','glowAnimated'],['hoverEnabled','hoverEnabled'],['wordmarkAuto','wordmarkAuto']].forEach(([id,key])=>$('#'+id).addEventListener('click',e=>{e.stopPropagation();state[key]=!state[key];syncUi();scheduleRender()}));
$('#presetPaletteBtn').addEventListener('click',()=>{state.colors=PRESETS[state.shaderMode].slice();if(state.shaderMode==='gradflow'){state.gradflowType='aurora';state.gradflowNoise=.2}syncUi();scheduleRender()});
$('#addLayerBtn').addEventListener('click',()=>addLayer('gradflow'));$('#addShadowBtn').addEventListener('click',()=>addLayer('vfxshadow'));
$('#replayBtn').addEventListener('click',replayIntro);$('#previewReplayBtn').addEventListener('click',replayIntro);
$('#savePresetBtn').addEventListener('click',()=>saveFile('star-shader-preset.json',JSON.stringify(exportPreset(),null,2),'application/json'));$('#exportHtmlBtn').addEventListener('click',()=>saveFile('tribute-star-animation.html',buildStandaloneHtml(),'text/html'));$('#copyPresetBtn').addEventListener('click',()=>copyText(JSON.stringify(exportPreset(),null,2)));$('#applyDumpBtn').addEventListener('click',()=>{try{applyPreset(JSON.parse(presetDump.value));toast('Preset applied')}catch{toast('Invalid JSON')}});$('#importFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)handleImport(f);e.target.value=''});

syncUi();renderPreview();
