const STAR_PATH=`M66.9629 0C67.879 0.166652 68.7864 0.351674 69.6846 0.555664L70.0586 0.772461C68.9674 12.7113 65.9785 36.5264 65.9785 36.5264L86.5537 42.1221L87.3721 43.5547L73.4893 48.4336C73.4893 48.4336 88.471 68.4575 96.5049 79.1787C95.9143 79.7262 95.3093 80.2623 94.6895 80.7861L63.0898 57.2207C59.7004 63.8131 46.9882 87.4847 43.667 93.666C42.509 93.4628 41.3648 93.2294 40.2354 92.9668L39.7812 92.5908C41.2618 77.7912 42.674 62.9069 43.501 48.0518C35.4293 45.9499 5.21554 38.569 0 37.2959C0.182283 36.5301 0.385424 35.7704 0.610352 35.0176C14.6821 33.9576 39.8564 31.917 39.8564 31.917L30.9717 15.1201L32.1143 14.4863C38.8474 19.2238 52.083 29.5917 52.1592 29.6514L66.9629 0Z`;
const STAR_VIEWBOX='0 0 96.5049 93.666'; const STAR_CENTER=[48.25245,46.833];
function starMaskUrl(){const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${STAR_VIEWBOX}"><path d="${STAR_PATH}" fill="white"/></svg>`;return `url("data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}")`; }
const PRESETS={strands:{colors:['#FF4242','#7C3AED','#06B6D4','#EAB308']},galaxy:{colors:['#FFFFFF','#D4D4D8','#A1A1AA','#71717A']},prismatic:{colors:['#FF4242','#7C3AED','#06B6D4','#EAB308']},siderays:{colors:['#EAB308','#93C5FD','#FFFFFF','#FFFFFF']},silk:{colors:['#8B5CF6','#4F46E5','#22D3EE','#E879F9']}};
const state={shaderMode:'strands',shaderRole:'fill',colors:['#FF4242','#7C3AED','#06B6D4','#EAB308'],speed:1,scale:1,intensity:1,opacity:1,introPreset:'settle',autoplayMode:'loop',revealDuration:1.25,revealDelay:0.1,morphStrength:0.45,overshoot:0.16,rotation:10,introBlur:4,glowEnabled:true,glowColor:'#FFFFFF',glowBlend:'screen',glowThickness:4,glowBlur:10,glowSpread:0.22,glowOpacity:0.85,glowDuration:3.6,glowFeather:0.45,bgMode:'dark'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s)); const shapeWrap=$('#shapeWrap'); const toastEl=$('#toast'); const presetDump=$('#presetDump'); let shaderCleanup=null; let renderTimer=0;
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),1600)}
function normHex(v){v=(v||'').trim().toUpperCase(); if(/^#[0-9A-F]{6}$/.test(v)) return v; if(/^#[0-9A-F]{3}$/.test(v)) return '#'+v.slice(1).split('').map(c=>c+c).join(''); return null;}
function exportPreset(){return JSON.parse(JSON.stringify(state));}
function syncBackground(){const card=$('#stageCard'), checker=$('#checker'); if(state.bgMode==='light'){card.style.background='radial-gradient(circle at top,rgba(0,0,0,.04),transparent 36%),#f4f4f5'; checker.style.opacity='.08';} else if(state.bgMode==='transparent'){card.style.background='transparent'; checker.style.opacity='.18';} else {card.style.background='radial-gradient(circle at top,rgba(255,255,255,.06),transparent 38%),#0f0f12'; checker.style.opacity='.15';}}
function syncUi(){['speed','scale','intensity','opacity','revealDuration','revealDelay','morphStrength','overshoot','rotation','introBlur','glowThickness','glowBlur','glowSpread','glowOpacity','glowDuration','glowFeather'].forEach(k=>{const el=$('#'+k); if(el) el.value=state[k]; const out=$('#'+k+'Val'); if(out) out.textContent=Number(state[k]).toFixed(k==='rotation'?0:2).replace(/\.00$/,'')}); ['shaderMode','shaderRole','introPreset','autoplayMode','glowBlend','bgMode'].forEach(k=>{const el=$('#'+k); if(el) el.value=state[k]}); state.colors.forEach((v,i)=>{$('#c'+(i+1)).value=v; $('#c'+(i+1)+'Text').value=v}); $('#glowColor').value=state.glowColor; $('#glowColorText').value=state.glowColor; $('#glowEnabled').classList.toggle('on',!!state.glowEnabled); syncBackground(); presetDump.value=JSON.stringify(exportPreset(),null,2)}
function bindHex(pair,index,target='colors'){const c=$('#'+pair),t=$('#'+pair+'Text'); c.addEventListener('input',()=>{t.value=c.value.toUpperCase(); state[target][index]=c.value.toUpperCase(); scheduleRender()}); t.addEventListener('change',()=>{const n=normHex(t.value); if(!n){t.value=state[target][index]; return;} c.value=n; t.value=n; state[target][index]=n; scheduleRender()});}
function buildSvg(){const baseVisible=state.shaderRole==='reveal'; return `<svg class="shape-svg shape-base" viewBox="${STAR_VIEWBOX}" xmlns="http://www.w3.org/2000/svg"><defs><filter id="glowBlurFilter" x="-120%" y="-120%" width="340%" height="340%"><feGaussianBlur stdDeviation="${state.glowBlur}"></feGaussianBlur></filter></defs><path id="shapeFillPath" d="${STAR_PATH}" fill="${baseVisible?state.colors[0]:'transparent'}" /></svg><canvas id="shaderCanvas" class="shader-layer" style="opacity:${state.opacity};mix-blend-mode:${state.shaderMode==='prismatic'?'lighten':'normal'}"></canvas><svg class="shape-svg glow-svg" viewBox="${STAR_VIEWBOX}" xmlns="http://www.w3.org/2000/svg" style="display:${state.glowEnabled?'block':'none'};mix-blend-mode:${state.glowBlend}"><path id="glowHalo" d="${STAR_PATH}" fill="none" stroke="${state.glowColor}" stroke-width="${state.glowThickness*2.2}" opacity="${Math.min(1,state.glowOpacity*.45)}" pathLength="100" stroke-dasharray="${state.glowSpread*100} ${100-state.glowSpread*100}" stroke-linecap="round" stroke-linejoin="round" filter="url(#glowBlurFilter)"/><path id="glowCore" d="${STAR_PATH}" fill="none" stroke="${state.glowColor}" stroke-width="${state.glowThickness}" opacity="${state.glowOpacity}" pathLength="100" stroke-dasharray="${Math.max(1,state.glowSpread*100*(1+state.glowFeather*.8))} ${100-Math.max(1,state.glowSpread*100*(1+state.glowFeather*.8))}" stroke-linecap="round" stroke-linejoin="round"/></svg><svg class="shape-svg shape-outline" viewBox="${STAR_VIEWBOX}" xmlns="http://www.w3.org/2000/svg" style="opacity:${state.shaderRole==='fill'?0:1}"><path id="outlinePath" d="${STAR_PATH}" fill="${state.colors[0]}" /></svg>`}
function pathNumbers(d){return d.match(/-?\d*\.?\d+(?:e[-+]?\d+)?/ig)?.map(Number)||[]}
function distortPath(d,strength,seed=1){if(strength<=0)return d; const nums=pathNumbers(d); let i=0; const [cx,cy]=STAR_CENTER; const rnd=n=>Math.sin(n*12.9898+seed*78.233)*43758.5453%1; return d.replace(/-?\d*\.?\d+(?:e[-+]?\d+)?/ig,m=>{const val=parseFloat(m); const idx=i++; const isX=idx%2===0; const pair=Math.floor(idx/2); const x=nums[pair*2]??val, y=nums[pair*2+1]??val; const dx=x-cx, dy=y-cy; const len=Math.hypot(dx,dy)+.0001; const radial=isX?dx/len:dy/len; const tang=isX?-dy/len:dx/len; const amp=14*strength*(.35+Math.min(1,len/45)); const delta=radial*(rnd(idx+1)-.5)*2*amp + tang*Math.sin(pair*.85+seed)*amp*.55; return String(Math.round((val+delta)*1000)/1000)})}
function animateGlow(){['#glowHalo','#glowCore'].forEach((sel,idx)=>{const p=$(sel,shapeWrap); if(!p)return; p.style.animation='none'; p.getBoundingClientRect(); p.style.animation=`glowOrbit ${state.glowDuration}s linear ${idx?0.08:0}s infinite`;});}
function shaderOpts(){return {mode:state.shaderMode,speed:+state.speed,scale:+state.scale,intensity:+state.intensity,opacity:+state.opacity,colors:state.colors.slice(),customColors:true}}
function renderPreview(){if(shaderCleanup){try{shaderCleanup()}catch{} shaderCleanup=null} shapeWrap.innerHTML=buildSvg(); const shader=$('#shaderCanvas',shapeWrap); const mask=starMaskUrl(); shader.style.webkitMaskImage=mask; shader.style.maskImage=mask; shader.style.webkitMaskRepeat=shader.style.maskRepeat='no-repeat'; shader.style.webkitMaskPosition=shader.style.maskPosition='center'; shader.style.webkitMaskSize=shader.style.maskSize='100% 100%'; try{shaderCleanup=runShaderCanvas(shader,shaderOpts())}catch(err){console.error(err); shader.style.display='none'; toast('Shader error: '+(err.message||'WebGL2 unavailable'))} animateGlow(); syncUi();}
function replayIntro(){const wrap=shapeWrap, duration=state.revealDuration*1000, delay=state.revealDelay*1000; const distorted=distortPath(STAR_PATH,state.morphStrength,Math.random()*10+1); ['#shapeFillPath','#outlinePath','#glowHalo','#glowCore'].forEach(sel=>{const el=$(sel,wrap); if(el) el.setAttribute('d',distorted)}); wrap.animate([{transform:`scale(0.06) rotate(${state.rotation}deg)`,filter:`blur(${state.introBlur}px) drop-shadow(0 12px 34px rgba(0,0,0,.45))`,opacity:0},{transform:`scale(${1+state.overshoot}) rotate(${state.rotation*0.22}deg)`,filter:'blur(0px) drop-shadow(0 20px 54px rgba(0,0,0,.55))',opacity:1,offset:.64},{transform:'scale(1) rotate(0deg)',filter:'blur(0px) drop-shadow(0 16px 60px rgba(0,0,0,.55))',opacity:1}],{duration,delay,easing:'cubic-bezier(.16,.84,.18,1)',fill:'both'}); const canvas=$('#shaderCanvas',wrap); if(state.shaderRole==='reveal'&&canvas) canvas.animate([{opacity:0,clipPath:'circle(0% at 50% 50%)'},{opacity:state.opacity,clipPath:'circle(76% at 50% 50%)',offset:.75},{opacity:0,clipPath:'circle(90% at 50% 50%)'}],{duration,delay,easing:'cubic-bezier(.16,.84,.18,1)',fill:'both'}); ['#glowHalo','#glowCore'].forEach((sel,idx)=>{const p=$(sel,wrap); if(!p)return; p.animate([{opacity:0,strokeDashoffset:100},{opacity:sel==='#glowCore'?state.glowOpacity:Math.min(1,state.glowOpacity*.45),strokeDashoffset:0}],{duration:duration*.7,delay:delay+duration*.18+idx*50,easing:'ease-out',fill:'both'})}); setTimeout(()=>['#shapeFillPath','#outlinePath','#glowHalo','#glowCore'].forEach(sel=>{const el=$(sel,wrap); if(el) el.setAttribute('d',STAR_PATH)}), duration+delay+40)}
function scheduleRender(){clearTimeout(renderTimer); renderTimer=setTimeout(()=>{renderPreview(); if(state.autoplayMode==='auto') replayIntro();},45)}
function saveFile(name,text,type='text/plain'){const blob=new Blob([text],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Copied')).catch(()=>toast('Copy failed'))}
function applyPreset(p){Object.assign(state,p); if(Array.isArray(p.colors)) state.colors=p.colors.slice(0,4); syncUi(); renderPreview(); replayIntro();}
function extractLegacy(html){const out=exportPreset(); const m=html.match(/runShaderCanvas\(shaderCanvas,\s*(\{[\s\S]*?\})\s*\)/); if(m){try{const obj=(new Function(`return (${m[1]})`))(); if(obj.mode) out.shaderMode=obj.mode; if(obj.speed!=null) out.speed=obj.speed; if(obj.scale!=null) out.scale=obj.scale; if(obj.intensity!=null) out.intensity=obj.intensity; if(Array.isArray(obj.colors)) out.colors=obj.colors.slice(0,4).map(v=>normHex(v)||'#FFFFFF')}catch(e){}} const dur=html.match(/smsReveal\w+\s+([\d.]+)s.*?\s([\d.]+)s\s+both/); if(dur){out.revealDuration=parseFloat(dur[1]); out.revealDelay=parseFloat(dur[2])} const halo=html.match(/sms-contour\.halo\{[^}]*stroke-width:([\d.]+);opacity:([\d.]+)/); if(halo){out.glowThickness=Math.max(1,parseFloat(halo[1])/2.2); out.glowOpacity=Math.min(1,parseFloat(halo[2])/.45)} const blur=html.match(/smsGlowWide[^>]*<feGaussianBlur stdDeviation="([\d.]+)"/); if(blur) out.glowBlur=parseFloat(blur[1]); return out}
function handleImport(file){const r=new FileReader(); r.onload=()=>{const text=String(r.result||''); try{ if(file.name.match(/\.json$/i)){applyPreset(JSON.parse(text)); toast('Preset JSON loaded'); return;} const m=text.match(/window\.SMS_V2_PRESET\s*=\s*(\{[\s\S]*?\});/); if(m){applyPreset(JSON.parse(m[1])); toast('Preset loaded from HTML'); return;} applyPreset(extractLegacy(text)); toast('Legacy HTML settings imported'); }catch(e){console.error(e); toast('Import failed')}}; r.readAsText(file)}
$$('.tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===btn));const tab=btn.dataset.tab;$$('.tab-panel').forEach(p=>p.hidden=p.dataset.panel!==tab)}));
[['shaderMode','shaderMode'],['shaderRole','shaderRole'],['introPreset','introPreset'],['autoplayMode','autoplayMode'],['glowBlend','glowBlend'],['bgMode','bgMode']].forEach(([id,key])=>$('#'+id).addEventListener('change',e=>{state[key]=e.target.value; scheduleRender()}));
[['speed','speed'],['scale','scale'],['intensity','intensity'],['opacity','opacity'],['revealDuration','revealDuration'],['revealDelay','revealDelay'],['morphStrength','morphStrength'],['overshoot','overshoot'],['rotation','rotation'],['introBlur','introBlur'],['glowThickness','glowThickness'],['glowBlur','glowBlur'],['glowSpread','glowSpread'],['glowOpacity','glowOpacity'],['glowDuration','glowDuration'],['glowFeather','glowFeather']].forEach(([id,key])=>$('#'+id).addEventListener('input',e=>{state[key]=parseFloat(e.target.value); scheduleRender()}));
bindHex('c1',0); bindHex('c2',1); bindHex('c3',2); bindHex('c4',3); $('#glowColor').addEventListener('input',e=>{state.glowColor=e.target.value.toUpperCase(); $('#glowColorText').value=state.glowColor; scheduleRender()}); $('#glowColorText').addEventListener('change',e=>{const n=normHex(e.target.value); if(!n){e.target.value=state.glowColor; return;} state.glowColor=n; $('#glowColor').value=n; e.target.value=n; scheduleRender()}); $('#glowEnabled').addEventListener('click',()=>{state.glowEnabled=!state.glowEnabled; scheduleRender()});
$('#presetPaletteBtn').addEventListener('click',()=>{state.colors=PRESETS[state.shaderMode].colors.slice(0,4); renderPreview(); replayIntro(); toast('Reference palette applied')}); $('#savePresetBtn').addEventListener('click',()=>saveFile('star-shader-preset.json',JSON.stringify(exportPreset(),null,2),'application/json')); $('#copyPresetBtn').addEventListener('click',()=>copyText(JSON.stringify(exportPreset(),null,2))); $('#applyDumpBtn').addEventListener('click',()=>{try{applyPreset(JSON.parse(presetDump.value)); toast('Preset applied')}catch(e){toast('Invalid JSON')}}); $('#replayBtn').addEventListener('click',()=>replayIntro()); $('#importFile').addEventListener('change',e=>{const f=e.target.files?.[0]; if(f) handleImport(f); e.target.value=''});
const extraStyle=document.createElement('style'); extraStyle.textContent='@keyframes glowOrbit{from{stroke-dashoffset:100}to{stroke-dashoffset:0}}'; document.head.appendChild(extraStyle);
syncUi(); renderPreview(); replayIntro();
